### ISSUE TITLE
Make Migrator configurable so it can be muted

### ISSUE THREAD

**Issue by konradreiche** [gobuffalo/pop#10]
`Migrator` makes use of `fmt.Printf` which makes it hard to mute. It's currently flooding parts of our outputs when we don't want it. I would prepare a pull request but it depends on the type of interface you would want to replace it if you want to replace it

https://github.com/gobuffalo/pop/blob/master/migrator.go#L66

**Comment by markbates** [comment]
How about a flag to suppress it?

-----------
Mark Bates

**Comment by glb** [comment]
It's not just `Migrator` -- there are 43 calls to `fmt.Print*` in this repository.

I'd love to see the various parts of `pop` support structured logging to a https://github.com/sirupsen/logrus `*logrus.Entry` that I can replace with my own, but would settle for a replaceable `log.Logger` that's called with the appropriate severity for the things getting logged.

I'd also settle for a flag that mutes all output, assuming that the `Migrator` will return enough information in the error it returns to do troubleshooting, but I'd prefer to see some logs.

**Comment by markbates** [comment]
I would love a PR for that.

-----------
Mark Bates

**Comment by stanislas-m** [comment]
Fixed with #186.
