### ISSUE TITLE
MySQL, i/o timeout on database creation, dropping.

### ISSUE THREAD

**Issue by sio4** [gobuffalo/pop#11]
Hello, I sent PR #9 for following issue. Please consider this PR.

The problem is, After SQL style database creation and dropping was implemented, and accordingly `mysql.urlWithoutDb()` was added, the method just returns auto-generated URL with `user`, `pass`, `host`, and `port`. In case of user specifiy connection information as URL, with options, it was ignored and hard coded default options are provided by the method.

In some condition, the default read timeout option (`readTimeout=1s`) is not enough and it makes operation failure. For example, when dropping existing database, and truncate all data for running test.

In my cases, I met following errors when I run my test cases on travis-ci:

````
[mysql] 2018/03/02 21:03:11 packets.go:33: read tcp 127.0.0.1:49306->127.0.0.1:3306: i/o timeout
[mysql] 2018/03/02 21:03:12 packets.go:33: read tcp 127.0.0.1:49308->127.0.0.1:3306: i/o timeout
[mysql] 2018/03/02 21:03:13 packets.go:33: read tcp 127.0.0.1:49496->127.0.0.1:3306: i/o timeout
````

and

```
--- FAIL: Test_ActionSuite (87.60s)
    --- FAIL: Test_ActionSuite/Test_RolesResource_A_Protected (3.00s)
        Error Trace:    model.go:20
                        suite.go:47
                        suite.go:88
        Error:          Received unexpected error:
                        driver: bad connection
                        <...>/gobuffalo/pop.(*Connection).timeFunc
                        <...>/gobuffalo/pop.(*Query).Exec
                        <...>/gobuffalo/pop.(*mysql).TruncateAll
```

mainly for TruncateAll, as see above.

After facing the issue, I tested it on my poor laptop, with limited resources, and I met another errors while just dropping the database:

```
$ buffalo db drop -e test
v4.0.6

[mysql] 2018/03/05 16:16:01 packets.go:36: read tcp 127.0.0.1:37106->127.0.0.1:3306: i/o timeout
<...>
```

Not for every running, but sometimes.

Anyway, I checked with the codes (from pop to database/sql because I cannot figure out the reason) and I found and fixed the method.

(Sorry for long history but I think it will help some others using `mysql`.)

**Comment by sio4** [comment]
Oh, case of `TruncateAll` is not directly related with this patch but it needs specific options like `readTimeout=2s`, with URL style of connection configuration. The timeout value can be configured according to user's environment. In my cases, sometime drop or migration exceeds slightly 1 second.

FYI, the reason of https://github.com/gobuffalo/pop/blob/master/.travis.yml#L17 is because when `buffalo db create` is running, with old style execution of CLI tool, the password part of the command was blank since travis-ci uses empty password for root. In mysql cli, empty password means interactive input from user terminal. It made infinite wait.

Anyway, with SQL style database creation and dropping, we can now use `buffalo db create` and `buffalo db drop` freely! (It takes some seconds so it will run after this PR was merged :-)

**Comment by markbates** [comment]
@sio4 I just merged https://github.com/gobuffalo/pop/pull/9 does that fix this issue? If so, can I close this? Thanks.

**Comment by sio4** [comment]
Thanks, I will check it by today (in KST)

**Comment by sio4** [comment]
Hi @markbates, Yes, it works fine!

After update, but with 1 second timeout, (for reference of old status)

```
$ time buffalo db drop -e test 
v4.1.0

[mysql] 2018/03/06 09:25:37 packets.go:36: read tcp 127.0.0.1:34396->127.0.0.1:3306: i/o timeout
[mysql] 2018/03/06 09:25:37 packets.go:37: buffer timeout:1s
couldn't drop database hc_uart_test: error dropping MySQL database hc_uart_test: invalid connection

real    0m1.047s
user    0m0.026s
sys     0m0.023s
<...>
```

and with 3s timeout option specified by URL form, It works without error!

```
$ time buffalo db drop -e test 
v4.1.0

dropped database hc_uart_test

real    0m1.139s
user    0m0.016s
sys     0m0.016s
<...>
```

Thanks! It works!

**Comment by markbates** [comment]
Don’t thank me: you fixed it. :)
