### ISSUE TITLE
Tagging on repository required

### ISSUE THREAD

**Issue by sio4** [gobuffalo/pop#13]
Hello @markbates,

I saw several version bumps on the commit logs and updated `version.so` of `soda` but anyway there is no tags since 4.0.6. I think we need tags so we can use `dep` correctly. Am I confused on versioning of `soda` and `pop` itself?

**Comment by sio4** [comment]
My mistake. Just single tag, 4.1.0 is missing on the repository.

**Comment by markbates** [comment]
It wasn't that it was missing, it was that I wasn't ready to release it yet, the tests were failing. It's released now.

**Comment by sio4** [comment]
Oh, I didn't check the commit/CI status. Sorry for my confusing.

**Comment by markbates** [comment]
No worries. :)
