### ISSUE TITLE
Feature Request - Custom path for models folder

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [gobuffalo/pop#16]
It is possible to specify custom path for migrations folder via `--path` flag. It would be neat if there was a way to specify custom path to models folder, when creating model with `soda generate model`.

**Comment by paganotoni** [comment]
@GrigoriyMikhalkin @stanislas-m In case the folder is specified, i get that that model should be generated in the specified folder, but should the folder name be used as the name of the package as well?

**Comment by stanislas-m** [comment]
@paganotoni That's a legit question. :) I'd say yes?
