### ISSUE TITLE
Eager doesn't work with pointers

### ISSUE THREAD

**Issue by josephbuchma** [gobuffalo/pop#161]
Usage of pointers allows direct marshalling without having undesired zero structs in JSON or whaterver.
```
type Post struct {
  // ...
  User *User `belongs_to:"user" json:"author"`
}
```
Eager loading `User` panics: `reflect: FieldByName of non-struct type`

**Comment by kteb** [comment]
Hello @josephbuchma, I've tried to reproduce the problem in https://github.com/kteb/test_pop but it seems  fine. I don't know if in between a commit fixed the problem. Could you try it again (make sure to have the latest version of pop).

**Comment by stanislas-m** [comment]
@josephbuchma, can you provide an example app or a piece of code allowing us to reproduce the problem? We'll need more details (OS, pop version, etc.)
