### ISSUE TITLE
pop-book/models package no longer available.

### ISSUE THREAD

**Issue by katpavlova** [gobuffalo/pop#166]
"bitbucket.org/pop-book/models" is no longer available, and I cannot seem to find it anywhere else online.
What should the models package be replaced with, for example when creating a new record:
`user := models.User{}`
or when querying records:
`users := []models.User{}
query := db.Where("id = 1").Where("name = 'Mark'")`

Is there a supported workaround for this lost functionality?

**Comment by markbates** [comment]
That repo isn't managed by this org. You would have to ask who ever owns that repo. Sorry. I'm not sure, but this might be what you're looking for https://andrew-sledge.gitbooks.io/the-unofficial-pop-book/content/.

**Comment by katpavlova** [comment]
Thank you for responding.
Both the book by Andre Sledge and your README file refer to this models package, so I was wondering how others are using pop to connect to their models from within go if this package no longer exists.
Or is the models package referred to in your README from a different repository? Could you please point me in its direction if that is the case?

**Comment by katpavlova** [comment]
Never mind, I'm sorry for bothering, I was thrown off by the import statement in the Unofficial pop book. I see now that models is a package built by soda in the "models" directory.
Apologies for the stupid question, thanks again for responding.
