### ISSUE TITLE
fizz: parse error: syntax error

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/pop#174]
The fizz file is [here](https://github.com/gobuffalo/pop/tree/master/migrations).

`PS C:\gopath\src\mall> buffalo db migrate up
v4.5.10

0.2450 seconds
Usage:
  buffalo db migrate up [flags]

Flags:
  -h, --help   help for up

Global Flags:
  -c, --config string   The configuration file you would like to use.
  -d, --debug           Use debug/verbose mode
  -e, --env string      The environment you want to run migrations against. Will use $GO_ENV if set. (default "development")
  -p, --path string     Path to the migrations folder (default "./migrations")

?[31mERRO?[0m[0000] Error: error processing migrations\20160808213308_setup_tests.up.fizz: could not fizz the migration migrations\20160808213308_setup_tests.up.fizz: parse error: syntax error`

PS C:\gopath\src\mall> buffalo info### Buffalo Version
v0.12.3

### App Information
Pwd=C:\gopath\src\mall
Root=C:\gopath\src\mall
GoPath=C:\gopath
Name=mall
Bin=bin\mall.exe
PackagePkg=mall
ActionsPkg=mall/actions
ModelsPkg=mall/models
GriftsPkg=mall/grifts
VCS=git
WithPop=true
WithSQLite=false
WithDep=true
WithWebpack=true
WithYarn=true
WithDocker=true
WithGrifts=true

### Go Version
go version go1.10.1 windows/amd64

### Go Env
set GOARCH=amd64
set GOBIN=C:\gopath\bin
set GOCACHE=C:\Users\zz\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\gopath
set GORACE=
set GOROOT=C:\go
set GOTMPDIR=
set GOTOOLDIR=C:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\z\AppData\Local\Temp\go-build994847302=/tmp/go-build -gno-record-gcc-switches

### Node Version
v8.11.3

### NPM Version
5.6.0

### Yarn Version
1.7.0

### PostgreSQL Version
PostgreSQL Not Found

### MySQL Version
MySQL Not Found

### SQLite Version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt2

### Dep Version
dep:
 version     : v0.4.1
 build date  : 2018-01-24
 git hash    : 37d9ea0a
 go version  : go1.9.1
 go compiler : gc
 platform    : windows/amd64

**Comment by stanislas-m** [comment]
Please upgrade to at least pop v4.5.12, this bug is already fixed.

**Comment by stanislas-m** [comment]
@paulZzhang You need to update buffalo too, since you're calling pop from buffalo.

In your logs, it says `v4.5.10`, which is the version of Pop called by buffalo. See https://blog.gobuffalo.io/pop-v4-6-0-released-bc9dc8f5eacb, paragraph "Buffalo version" to upgrade your Buffalo install.

**Comment by paulZzhang** [comment]
@stanislas-m The Buffalo window version is old.Please update it.
```
scoop install buffalo
```
