### ISSUE TITLE
The migration time is bad.

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/pop#176]
![image](https://user-images.githubusercontent.com/38898036/42944249-bb2c791e-8b97-11e8-8139-aba5b0ffdd71.png)
![image](https://user-images.githubusercontent.com/38898036/42944262-c20b4e04-8b97-11e8-8615-3306cb024e1e.png)

**The actual time is 20180719210935**
![image](https://user-images.githubusercontent.com/38898036/42944377-12a4dcd6-8b98-11e8-90a7-8ff263f294b0.png)

**Comment by markbates** [comment]
The time stamp is in UTC, not local to keep uniformed regardless of the tz it was created in. Feature, not bug. :)

**Comment by paulZzhang** [comment]
@markbates Please support the local time. Thanks.

**Comment by paulZzhang** [comment]
Yeah.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________
