### ISSUE TITLE
Please support the seed data. 

### ISSUE THREAD

**Issue by paulZzhang** [gobuffalo/pop#182]
The rails framework has[ db:seed](http://guides.rubyonrails.org/active_record_migrations.html) command. 

The laravel framework has [php artisan db:seed](https://laravel.com/docs/5.6/seeding) 

Please support the seed data.

**Comment by markbates** [comment]
buffalo task db:seed

It’s genreated with buffalo new.

**Comment by markbates** [comment]
We accept PRs for documentation. Please contribute docs to help those down the line. The core team can only do so much. :)

--
Mark Bates

**Comment by markbates** [comment]
Also, those frameworks have been around for a decade. That’s a long time to get docs. Buffalo is new.

--
Mark Bates
