### ISSUE TITLE
GoDoc 

### ISSUE THREAD

**Issue by kteb** [gobuffalo/pop#187]
On https://godoc.org/github.com/markbates/pop (it's the first one I fount through google when I looked at `golang doc pop`) there is no mention  that the repo moved. I thought even if it supposed to be frozen, maybe you can just make a last commit to update the doc. 

I'll take this issue also to add a small administrative issue, could you contact github support to ask them to change gobuffalo/pop as the reference and not a fork (I've looked at it once, and you need to do it by email). So it will remove here `forked from markbates/pop` and in markbates/pop it will add `forked from gobuffalo/pop`, the only reason I'm asking this, is that sometimes I'm using github search inside the code and it's not possible on forked repo.

**Comment by markbates** [comment]
Thanks! This is top of my todo list tomorrow. Very much appreciated. There are a few other repos that I need to get re-“forked” as well.

--
Mark Bates

**Comment by markbates** [comment]
Done! Thanks!
