### ISSUE TITLE
Migrate to gofrs/uuid from gobuffalo/uuid

### ISSUE THREAD

**Issue by markbates** [gobuffalo/pop#188]
This is a properly maintained community fork of the uuid project. I suggest we migrate users and pop to this new package. 

https://github.com/gofrs/uuid/releases/tag/v2.0.0

**Comment by kteb** [comment]
I think it could be good, just let see how they go with go modules before updating the project.

**Comment by theckman** [comment]
I just merged the module file so I think we should be good to go here. Do y'all need help with having this done?

**Comment by stanislas-m** [comment]
Waiting for https://github.com/gofrs/uuid/pull/66.

**Comment by stanislas-m** [comment]
Merged in development, waiting for the next minor release.
