### ISSUE TITLE
[Question] Is there a reason for models.Validate requiring a *pop.Connection?

### ISSUE THREAD

**Issue by katpavlova** [gobuffalo/pop#193]
Example:
```
func (v *Variant) Validate(tx *pop.Connection) (*validate.Errors, error) {
	return validate.Validate(
		&validators.StringIsPresent{Field: v.Chromosome, Name: "Chromosome"},
		&customValidators.IntIsNotNull{Field: v.Start, Name: "Start"},
		&validators.StringIsPresent{Field: v.Ref, Name: "Ref"},
		&validators.StringIsPresent{Field: v.Alt, Name: "Alt"},
	), nil
}
```
I would like to be able to Validate a model prior to creation in the model transformation step and then Save to the database later, which seems to be permitted by the executors. However I can't seem to understand why the *pop.Connection is needed as a parameter to the model's Validate function, as the Connection is not used by the function nor by any of its calls. If possible I would like to minimize needless passing of this connection, is it safe to modify the signature of the Validate function?

Thank you very much!

**Comment by stanislas-m** [comment]
That's because you can do the following: https://github.com/gobuffalo/authrecipe/blob/master/models/user.go#L60; so that's why it's required. :)

**Comment by paganotoni** [comment]
Great example @stanislas-m !

**Comment by katpavlova** [comment]
@stanislas-m Great, thank you so much.

**Comment by stanislas-m** [comment]
Np!
