### ISSUE TITLE
Migrate inflect to flect

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/pop#194]
https://github.com/gobuffalo/flect is a new simplified version of inflect, the package used to handle text transformations (snake_case, camelCase, and so on).

**Comment by u007** [comment]
custom made flect ?

**Comment by kteb** [comment]
Mark created during his holiday a new inflection library: https://github.com/gobuffalo/flect, that is suppose to replace inflect in all buffalo projects.

**Comment by u007** [comment]
awesome :)

**Comment by stanislas-m** [comment]
Fixed with #219.
