### ISSUE TITLE
Don't Convert ID Used in Queries to int if Column Type is string

### ISSUE THREAD

**Issue by Mohammed90** [gobuffalo/pop#195]
Pop now supports string-typed ID columns by the virtue of this commit https://github.com/gobuffalo/pop/commit/755b8933387a2722403dd7337cb207158d1a29d9 . However, the line referenced below breaks it if the ID is stringly-typed numbers:

https://github.com/gobuffalo/pop/blob/c0faa0f7edf8c0db4befe9abc41d135003a97d53/finders.go#L38

For my use-case, my unique set has IDs that could be '001' or '123'. They're unique, so I should be able to use them as the ID. They're saved properly, but cannot be queried because the line referenced above keeps truncating leading zeros.

**Comment by stanislas-m** [comment]
Fixed with #208.
