### ISSUE TITLE
CreatedAt & UpdatedAt with UNIX timestamp

### ISSUE THREAD

**Issue by cylin743** [gobuffalo/pop#196]
Hello

Is there a way to use unix timestamp (1559222400), but not datetime format?

https://github.com/gobuffalo/pop/blob/master/model.go#L142-L154

**Comment by stanislas-m** [comment]
Hello @cylin743, can you provide more details on what you want? When you said UNIX timestamp, is it on the database side? On the Go side?

**Comment by cylin743** [comment]
Both, I want to store created_at and updated_at with unix timestamp (int) in database. Also, I want to get created_at & updated_at with "int" in Go.

**Comment by stanislas-m** [comment]
Fixed with #215. You'll need to disable auto timestamps if you use fizz, but it should work.
