### ISSUE TITLE
DumpSchema can log database credentials

### ISSUE THREAD

**Issue by jim** [gobuffalo/pop#2]
When running `soda migrate -d` in a project using Pop, the last line logged out when the schema is dumped can contain the database URL and therefore the username and password used to connect to it:

```
    "[POP] 2018/02/21 21:53:23 pg_dump -s --dbname=postgres://USERNAME:PASSWORD@host:5432/app?sslmode=disable"
```

This project is using `-d` to make the SQL being run against the database in the migrations visible, but ideally we can avoid leaking credentials in order to achieve that.

The code that logs this message is in [`postgresql.go` in `DumpSchema`](https://github.com/gobuffalo/pop/blob/aa0c156c05776b317c420a92bcf89fe05cd646a2/postgresql.go#L176), although I imagine that it also affects some of the other database types.

I'd like to address this issue and am planning to open a pull request to do so. My initial thought was to just not print out the database URL and avoid the issue that way. What do you think of that approach?

**Comment by markbates** [comment]
I'm torn. The `-d` flag is meant for debugging purposes, which could include trying to figure out why it's not connecting, and hiding the connection info takes away from the intended purpose of the flag.

On the other hand, we don't want to leak information. The simple solution is to just not use the `-d` flag in production, then the info is safe.

But I'm open to suggestions on how to maintain the usefulness of the `-d` flag, but at the same time, make it secure.

**Comment by jim** [comment]
What do you think about having `soda migrate` print some other output as each migration is run? We wouldn't need to use `-d` to gain this insight or complicate how the debug output was currently being handled.

How about something like this:

```
$ soda migrate up
v3.51.1
Migrating up...
  20180103215841_create_posts
  20180205233329_create_comments

0.0209 seconds
dumped schema for datebase_name
```

This could be the default, which I think would be OK, or hidden behind a flag.

**Comment by markbates** [comment]
I believe the default for migrate is to print the name of the migrations and the times. Adding the database it’s migrating would be a good addition.

**Comment by jim** [comment]
You're right! I had missed that.

I think I'll close this for now, as the immediate need is already supported. Thanks for helping me work through this issue.

**Comment by markbates** [comment]
No worries. Happy to help. 🙂
