### ISSUE TITLE
Fix brakes add_foreign_key

### ISSUE THREAD

**Issue by cimnine** [gobuffalo/pop#212]
## Description

The `fix` package blindly replaces `})` with `}`, unaware of context.

### Steps to Reproduce the Problem

```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE",
})
```

Run `buffalo db fix`, get this:

```
add_foreign_key("domains", "domain_id", {"domains": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE",
}
```

### Expected Behavior

Don't introduce a syntax error. Also a check after the "fix" operation that the syntax of the result is still valid and roll the changes back otherwise.

### Actual Behavior

`fix` removes a `)` where it shouldn't.

#### Workaround

As a workaround, type `add_foreign_key` migrations (and similar) as follows:

```
add_foreign_key("domains", "domain_id", {"rules": ["id"]}, {
    "name": "fk_rules_domains",
    "on_delete": "CASCADE",
    "on_update": "CASCADE", })
```

I.e. don't let the `})` be on it's own line.

#### Cause

https://github.com/gobuffalo/pop/blob/7bb873077bba624e819348fe6ef605bc891b5069/fix/anko.go#L20-L22

This part is not implemented "context aware".

**Comment by mclark4386** [comment]
Good catch! Thanks for running this down!

**Comment by cimnine** [comment]
How does this fix work? When the condition on line 17 is true, how can the nested condition on line 19 become true? What am I missing here?
