### ISSUE TITLE
Key Length for MariaDB

### ISSUE THREAD

**Issue by lapubell** [gobuffalo/pop#224]
## Default schema.sql wants to use a key length not supported by latest MariaDB

This line ``` `version` varchar(255) NOT NULL``` inside migrations/schema.sql doesn't work with older versions of MySQL or MariaDB. The key should only be 191 long to make the UTF8 character encoding happy.

### Steps to Reproduce the Problem

  1. Setup a new buffalo project with the DB set to MySQL
  2. Try to create and migrate the DB
  3. See the error:
```
ERRO[0000] Error: Migrator: problem creating schema migrations: CREATE TABLE `schema_migration` (
`version` VARCHAR (255) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX `schema_migration_version_idx` ON `schema_migration` (`version`);: Error 1071: Specified key was too long; max key length is 767 bytes
```

### Expected Behavior

I'd love it if there was a way to say
```
buffalo new --db-type=mariadb
```

and it would set the version varchar to 191 in length.

### Info

You're not alone in this! [Here's a blog post from the laravel community about how to fix this issue for a Laravel app](https://laravel-news.com/laravel-5-4-key-too-long-error/).

**Comment by stanislas-m** [comment]
The original issue was fixed a long time ago, but we still need to create a driver for mariaDB to be able to do `buffalo new --db-type=mariadb`.
