### ISSUE TITLE
Empty schema.sql files shouldn't be written

### ISSUE THREAD

**Issue by markbates** [gobuffalo/pop#225]
Occasionally, the schema.sql file generated is empty, causing problems down the line.

I've seen this happen several times in class today where students had a tool like PGAdmin open and Postgres dumped an empty schema.sql file and `buffalo test` failed to run properly.

**Comment by mclark4386** [comment]
So maybe the other tool had a lock on all the open connections? hmmm... Will have to look into it...

**Comment by stanislas-m** [comment]
This should be fixed in v4.9.0.

**Comment by stanislas-m** [comment]
I still can reproduce in v4.9.0.
