### ISSUE TITLE
Support binary UUID columns in MySQL

### ISSUE THREAD

**Issue by cce** [gobuffalo/pop#243]
What would be the best way to add support for pop to use `BINARY(16)` rather than `CHAR(36)` for UUID primary key columns using MySQL? It seems fizz [maps the uuid type to char(36)](https://github.com/gobuffalo/fizz/blob/f57f22e853fa196e6e0048979cedba8219fa41d1/translators/mysql.go#L230) and the pop `whereID()` helper method [assumes non-integer IDs can be formatted with %s](https://github.com/gobuffalo/pop/blob/2b6e2a4c979e204a9e61b95ed419780493940079/model.go#L174-L175) and surrounded with single quotes in a SQL query.

Curious your opinion on the best approach with minimal impact to pop — I am using SQL migrations (so didn't run into the fizz issue) and tried providing an alternate uuid.UUID / driver.Valuer implementation to return `[]byte` rather than a `string`, but ran into the `whereID` issue. Would you take a PR adding a PrimaryKeyer interface or something?

**Comment by stanislas-m** [comment]
It should work with the next version. :)

**Comment by stanislas-m** [comment]
Fixed with #249.

**Comment by cce** [comment]
Thanks!
