### ISSUE TITLE
command line option -e is ignored when GO_ENV is defined in .env file

### ISSUE THREAD

**Issue by armhold** [gobuffalo/pop#269]
### Steps to Reproduce the Problem

In a dir with a .env containing `GO_ENV=development` , run 

  1. `soda migrate -e test`

### Expected Behavior

The `test` environment should be used when `-e test` arg is given.

### Actual Behavior

The `development` environment is used, ignoring the command line flag.

It's also surprising to me that the `.env` file will override `GO_ENV`. I.e. `GO_ENV=test soda migrate` will also defer to the `.env` file... is that intended?

### Info

macOS 10.13.6, using latest pop (git: 0596d299dc4e19f8639d15006e4984853e6c0087)

**Comment by sio4** [comment]
I also faced this problem.
Stored environment using `.env` is a nice feature but command line value and environment variables always should have most priority than file given one.

**Comment by sio4** [comment]
Still, the same issue happens:

```console
$ soda reset -e test
pop v6.0.2

[POP] 2022/06/04 20:40:03 info - drop app_development (...)
Error: couldn't drop database app_development: error dropping...
```

the database should be `app_test` for this case.
