### ISSUE TITLE
PR for fixing bugs on cockroach connection not merged properly.

### ISSUE THREAD

**Issue by sio4** [gobuffalo/pop#279]
Hi, @markbates, @stanislas-m,
I PRed #271 for fixing some problem on dialect for cockroach and connection and it marked as merged. But in fact, the merge does not contain my commits. What is happen? Is there any problem with the PR?

If then, let me know so I can fix it.

The PR fixed many connection problems for cockroach including more flexible option handling especially for the secure connection, make usable URL for both query and database handling like create database and others, bug on regex, and so on.

**Comment by stanislas-m** [comment]
@sio4 That's a merge problem, I probably had to resolve conflicts and erased your changes by mistake. Sorry, I'll take a look at this.

**Comment by sio4** [comment]
Hi @stanislad-m,
No problem! I live in +0900 timezone, Korea, and while I sleep, I becoming to know why it happen! And I wake up in the earrrrrrly! (It's not happen usually :-)

Some day before I heard about github system failure. Maybe it affected! Don't worry. I also have another change on cockroach for Truncate bug so I will open new one.

**Comment by sio4** [comment]
PRed as #280
