### ISSUE TITLE
Support for enum types

### ISSUE THREAD

**Issue by AaronVasquez** [gobuffalo/pop#28]
Is this supported?

**Comment by markbates** [comment]
Depends on your definition of "supported", I guess. Any type you put into fizz will be passed through directly to the database if fizz doesn't know what to do with it. So it will work with any database type you give it. On the Go side you have to use a type that would support the database type you want to use. Does that help?

**Comment by AaronVasquez** [comment]
Can you help guide me on how to use this with fizz: 
https://www.postgresql.org/docs/10/static/functions-enum.html

**Comment by markbates** [comment]
In that case just use a `*.sql` migration to create the enum type.
