### ISSUE TITLE
When or where is the best place to call `LoadConfigFile()`?

### ISSUE THREAD

**Issue by sio4** [gobuffalo/pop#284]
While I test pop, I found `LoadConfigFile()` is called several times for one execution (for example single `soda` execution).

The first occurrence on the file is this:

https://github.com/gobuffalo/pop/blob/9c8883450d22d078ee2daeacf47c37f9f213bde4/config.go#L38

But since it executed by `init()`, and there are other `init()` around and `init()` for dialect register them to global variables, sometimes it failed to load some of the configured connection and make warnings. I think `init()` is good to check it immediately but not a good place for it.

And just before all `LoadConfigFile()` by `init()`, it can also call `AddLookupPaths()` and it returns `LoadConfigFile()`. 

https://github.com/gobuffalo/pop/blob/9c8883450d22d078ee2daeacf47c37f9f213bde4/config.go#L71

I think this is not a good place for `LoadConfigFile()`. Is there any reason?

Finally, There is another place to call `LoadConfigFile()`.

https://github.com/gobuffalo/pop/blob/9c8883450d22d078ee2daeacf47c37f9f213bde4/connection.go#L79

Just before connect. It is good and the safest place to execute it.

**Comment by stanislas-m** [comment]
I agree there are too many places where the config is loaded. I think we shouldn't load the config in the init: pop is a library, and loading the config should be a lib user choice.

**Comment by sio4** [comment]
see also #289

**Comment by sio4** [comment]
Closed by #289
