### ISSUE TITLE
"Buffalo setup" fails at migrations

### ISSUE THREAD

**Issue by tadeogutierrez** [gobuffalo/pop#297]
When running Buffalo setup in a MySQL app, it fails the migration step. All dependencies and database creation commands are successful, but I get the following error when it gets to the "buffalo pop migrate " command:

_Error: Migrator: problem creating schema migrations: CREATE TABLE `schema_migration`_

### Step to reproduce:

**1. Create a new MySQL application:**
     buffalo new mysql_app --db-type mysql -v
    (Edit database.yaml with mysql credentials) 

**2. Run "buffalo setup -v"**

INFO[0000] --> yarnpkg install --no-progress            
yarn install v1.10.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.38s.
INFO[0000] --> dep ensure -v                            
INFO[0000] --> buffalo pop create -a                    
v4.8.5

[POP] 2018/10/26 13:46:41 info - create mysql_app_development (root:********@(localhost:3306)/mysql_app_development?parseTime=true&multiStatements=true&readTimeout=1s&collation=utf8mb4_general_ci)
[POP] 2018/10/26 13:46:41 info - created database mysql_app_development
[POP] 2018/10/26 13:46:41 info - create mysql_app_test (root:d3vus3r@(localhost:3306)/mysql_app_test?parseTime=true&multiStatements=true&readTimeout=1s)
[POP] 2018/10/26 13:46:41 info - created database mysql_app_test
[POP] 2018/10/26 13:46:41 info - create mysql_app_production (root:d3vus3r@(localhost:3306)/mysql_app_production?parseTime=true&multiStatements=true&readTimeout=1s)
[POP] 2018/10/26 13:46:41 info - created database mysql_app_production
INFO[0001] --> buffalo pop migrate                      
v4.8.5

[mysql] 2018/10/26 13:46:43 packets.go:36: read tcp 127.0.0.1:43408->127.0.0.1:3306: i/o timeout
[POP] 2018/10/26 13:46:43 info - 1.6048 seconds
mysqldump: [Warning] Using a password on the command line interface can be insecure.
[POP] 2018/10/26 13:46:43 info - dumped schema for mysql_app_development
Error: Migrator: problem creating schema migrations: CREATE TABLE `schema_migration` (
`version` VARCHAR (255) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX `schema_migration_version_idx` ON `schema_migration` (`version`);: invalid connection
Usage:
  buffalo-pop pop migrate [flags]
  buffalo-pop pop migrate [command]

Aliases:
  migrate, m

Available Commands:
  down        Apply one or more of the 'down' migrations.
  reset       The equivalent of running `migrate down` and then `migrate up`
  status      Displays the status of all migrations.
  up          Apply all of the 'up' migrations.

Flags:
  -h, --help   help for migrate

Global Flags:
  -c, --config string   The configuration file you would like to use.
  -d, --debug           Use debug/verbose mode
  -e, --env string      The environment you want to run migrations against. Will use $GO_ENV if set. (default "development")
  -p, --path string     Path to the migrations folder (default "./migrations")

Use "buffalo-pop pop migrate [command] --help" for more information about a command.

Migrator: problem creating schema migrations: CREATE TABLE `schema_migration` (
`version` VARCHAR (255) NOT NULL
) ENGINE=InnoDB;
CREATE UNIQUE INDEX `schema_migration_version_idx` ON `schema_migration` (`version`);: invalid connection
Usage:
  buffalo pop [flags]

Aliases:
  pop, db

Flags:
  -h, --help   help for pop

ERRO[0001] Error: exit status 1
                        
Usage:
  buffalo setup [flags]

Flags:
  -d, --drop      drop existing databases
  -h, --help      help for setup
  -u, --update    run go get -u against the application's Go dependencies
  -v, --verbose   run with verbose output

ERRO[0002] Error: We encountered the following error when trying to migrate your database:
exit status 255

**This happens even if the databases are dropped with the "-d" option**

**Comment by sio4** [comment]
Hi, Can you try it again with the following option?

```yaml
development:
  url: root:d3vus3r@(localhost:3306)/mysql_app_development?parseTime=true&multiStatements=true&readTimeout=5s&collation=utf8mb4_general_ci
```

Different from your current configuration is:
1) using `url` instead of `host`, `port`, `user`,... (just guessed)
2) changed `readTimeout` from 1s to 5s.

You need to use `url` key to tune details of connection parameters since you use v4.8.5 of pop which does not support fine tuning with `options` (pop support detail parameter configuration with `option` since v4.9.0).

In my test, migration took 0.1s to 1.5s and if the readTimeout is less than this, it makes that error.
(underlying MySQL driver makes `ErrBadConn` and this connection cannot be reused as I remember)

**Comment by sio4** [comment]
Hi @tadeogutierrez,
Did you try with the above configuration? Anyway, the fix for changing default timeout was merged into master. Can you try with pop version 4.9.1 or above to check this problem is solved?

By the way, now you can configure detail parameters with `options` key.

**Comment by shanmugharajk** [comment]
Hi @sio4 

I ran into similar problem. When I run `buffalo pop create -a` it just prints the version as `v4.11.0` and nothing happens after. The database itself is not getting created.

Could you please help me!

**Comment by shanmugharajk** [comment]
I am extremely sorry, It's my bad mistake my connection information was wrong. Since it didn't give error I was confused. Its working now!

Thanks!

**Comment by stanislas-m** [comment]
I'm closing this one since a solution was provided and it's quite old. Please feel free to open another issue if you still have problems with the latest version.
