### ISSUE TITLE
Feature Request - Ability to specify the position a new column is created in a table

### ISSUE THREAD

**Issue by alexsante** [gobuffalo/pop#3]
There are times when a new column needs to be added to a table, but there is currently no way to tell Fizz in what order to place that new column.  Mysql allows you to specify a `BEFORE` or `AFTER` command followed by the target column.

**Comment by alexsante** [comment]
I started working on this feature here: https://github.com/gobuffalo/pop/pull/6

**Comment by stanislas-m** [comment]
Covered by #6.
