### ISSUE TITLE
SHOULDERS.md

### ISSUE THREAD

**Issue by i4o** [gobuffalo/pop#303]
### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. open your README.md
  1. click link to check SHOULDERS.md
  

### Expected Behavior

open link with  file

### Actual Behavior

404

### Info

n/a

**Comment by stanislas-m** [comment]
This is a bug from our release tool, it will be fixed with https://github.com/gobuffalo/release/pull/5.

**Comment by stanislas-m** [comment]
Fixed in v4.9.1.
