### ISSUE TITLE
Fizz migration doesn't create id field on postgresql

### ISSUE THREAD

**Issue by sunho** [gobuffalo/pop#306]
### Steps to Reproduce the Problem

database.yml:
```
development:
  dialect: postgres
  database: gorani2
  host: 127.0.0.1
  pool: 5
```

fizz file:
```
create_table("users") {
  t.Column("username", "string", {})
  t.Column("email", "string", {})
  t.Column("password_hash", "string", {})
}
```

I ran "soda migrate" with files above.

### Expected Behavior

Automatically generated id field with auto increment and primary key as the doc says.

### Actual Behavior

But in dumped sql, id field wasn't created.

```

--
-- Name: users; Type: TABLE; Schema: public; Owner: sunho
--

CREATE TABLE public.users (
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```

### Info

Pop v4.9.0
Soda v4.9.0
Postgresql 10.5

**Comment by sio4** [comment]
How did you make the fizz file? Did you generate the file by hands or using `soda`? Currently, Fizz does not automatically generate an ID for the table but just do its own job with given `*.fizz` file. If you use `soda` (or `buffalo pop`) to generate `*.fizz`, `soda` does add missing ID for you.

**Comment by stanislas-m** [comment]
The behavior your describe is the correct one. Fizz no longer magically
adds the ID column, but the soda generator does add it for you in the fizz
definition.

-- 
*Stanislas MICHALAK*

**Comment by stanislas-m** [comment]
@sio4 Just updated the Fizz README.md. :)
