### ISSUE TITLE
CSV loader

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/pop#32]
## Abstract

For testing purposes, it's quite common to preload some known data in the database. CSV files are a good way to handle data rows, and many data-manipulation tools have a support for CSV extraction.

## Implementation

* The first line of the CSV file will contain the column names
* Next lines will contain the data
* Each data row will be converted by the new module to pop SQL inserts.
* The query can be prepared and reused, since it will use the same INSERT query, but with different data.

**Comment by markbates** [comment]
I was thinking more along the lines of what Rails does with fixtures http://guides.rubyonrails.org/testing.html#the-low-down-on-fixtures

**Comment by markbates** [comment]
Never mind, I thought this was about loading test data in buffalo. Ignore my previous comment. :)

**Comment by stanislas-m** [comment]
@markbates It can be used for that, but it aims to be more generic and not Buffalo-centric.

**Comment by hobbeshunter** [comment]
So there is currently no way to load test data for testing or development? Well then I would like to make a feature request :D

Btw: great work

**Comment by markbates** [comment]
See https://github.com/gobuffalo/suite/pull/8 it’ll be merged tomorrow.

**Comment by hobbeshunter** [comment]
Thanks a lot for this. It already looks great.

Something I also would like to have is a command like `buffalo db populate scenario-dev`. Lets say I have my app running for development with `buffalo dev` and then I want to populate my database with some examples.

**Comment by markbates** [comment]
I think you want the db:seed task. `buffalo t db:seed`. Look in grifts/db.go. Fill that with whatever you need, run it, populated db.

**Comment by stanislas-m** [comment]
Closing this one, will be implemented outside the repo as a plugin.
