### ISSUE TITLE
how to do a select where attribute in ? in sqlite

### ISSUE THREAD

**Issue by delfick** [gobuffalo/pop#340]
hi,

How do I do a `db.Where("attribute IN ?", someSliceOfStrings)` when the database is sqilte?

In Postgres I would do `db.Where("attribute = ANY(?)", pq.Array(someSliceOfStrings))` but I can't figure out how to do it with sqlite

The first way just errors out with `"sqlite select many: sql: converting argument $2 type: unsupported type []string, a slice of string"`

**Comment by delfick** [comment]
so from that I can pass in multiple arguments but it seems I can't do that.

For example, if I say

```
s.db.Where("token_id IN (?)", tokenIDs...).All(&result)
```

I get a compiler error `cannot use tokenIDs (type []string) as type []interface {} in argument to s.db.Where`

**Comment by markbates** [comment]
You need to convert them to an []interface type as per Go’s error.

**Comment by delfick** [comment]
aaaahhhh! I see. Yeap, that works. Thanks :)

**Comment by markbates** [comment]
I’m on a phone that’s the best I can do. Go requires a slice of interfaces if you don’t pass the Args by hand. Then use ...
