### ISSUE TITLE
LIKE not working with sqlite3

### ISSUE THREAD

**Issue by Herobs** [gobuffalo/pop#352]
As mentioned in title, the following code not working in sqlite3
```
query.Where("name LIKE '%?%'", keyword)
```

However if I construct manually, it just work. But I cant find any escape function in pop, database/sql or sqlite3 package for preventing SQL inject attack.
```
query.Where(fmt.Sprintf("name LIKE '%%%s%%'", keyword))
```

Thanks.

**Comment by jh125486** [comment]
Can you try? 
```
query.Where("name LIKE ?", "%"+keyword+"%")
```

It may work because I think the execute already does the quoting around the placeholder.

**Comment by Herobs** [comment]
@jh125486 It works. Thanks very much.

After simple test, it seems sql inject not happened.
