### ISSUE TITLE
tx.Where() : `?` interpolation fails silently when used on the column name

### ISSUE THREAD

**Issue by BastienM** [gobuffalo/pop#377]
## Description

`pop` fails silently when using the interpolation on the column name inside a `Where()` or `RawQuery()` (that I know of) clause.

### Steps to Reproduce the Problem

To give more context, I have a use case where I have to dynamically query a model's field based on a `switch` condition.

As the doc shows interpolation being done via the `?` char in the examples, one can think that it can be used in a more generic way.

Which results in the following code :

```go
dbColumn := "name"
value := "martin"
u := &models.User{}
err := tx.Where("? = ?", dbColumn, value).First(u)
```

### Expected Behavior

A more targeted error message to imply an error occured in the interpolation process.

**OR**

Have the same behavior `Printf()` has with `%`:
```go
fmt.Printf("%s = %s", dbColumn, value)
```

Or Python's `str.format()` :
```python
"{0} = {1}".format(dbColumn, value)
```

### Actual Behavior

Silently fails by returning `sql.ErrNoRow`.

Right now the only way to do that is in two steps :

```go
qst := fmt.Sprintf("%s = ?", dbColumn)
err := tx.Where(qst, value).First(u)
```

### Info

**OS**: Archlinux `5.0.7-arch1-1-ARCH`
**Go**: `go version go1.12.4 linux/amd64`
**Buffalo**: `Buffalo version is: v0.14.1`

**Comment by mclark4386** [comment]
Hey @BastienM , Thank you for your input!  This is actually intended behavior as a method to prevent SQL injection. If you really need to set the columns dynamically then your workaround in **Actual Behavior** is the recommended way of doing this. I would warn to be VERY careful with this though.
Thanks!
-Matt

**Comment by BastienM** [comment]
Hi @mclark4386,

Thank you for the quick response.
Maybe a quick note in the documentation on how `pop` tackles SQL injection would be appreciated, or is by design as well ?

I use reflection on my own struct to select the column, so that should be fairly secure (to me at last), whereas the user's input is injected via the current interpolation process.

**Comment by mclark4386** [comment]
Prepared statements being treated that way isn't a pop specific thing, but a prepared statements thing. That said if you aren't using user generated content for the column names I see no reason not to use the `Sprintf` method to prep the statement^^

Documentation PRs are always welcome ;)
Cheers!
