### ISSUE TITLE
Add instructions for installing soda with sqlite3 support to README

### ISSUE THREAD

**Issue by bigblind** [gobuffalo/pop#38]
I ran into trouble when I added an sqlite3 database configuration to my yaml file. Sodawas telling me that no connection with the requested name exists. I remembered sqlite3 support was removed from the default build of buffalo, so I assumed this means the same would be true for soda, so I took the following steps:

- Re-install buffalo with sqlite3 support: `go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo`
- Use the same flag to update pop: `go get -u -v -tags sqlite github.com/gobuffalo/pop/...`
- Install `soda` with these flags: `go install -v -tags sqlite github.com/gobuffalo/pop/soda`

After these steps, it works as expected.

I'd like to submit a PR to update the README, but I'm not sure which of these steps are actually necessary.

**Comment by markbates** [comment]
So this will download, then build & install, Buffalo with SQLite support:

```
go get -u -v -tags sqlite github.com/gobuffalo/buffalo/buffalo
```

That's already documented. If you don't need the actual `soda` binary, you're done. :) `buffalo db` is, for all intentions, identical to `soda`.

We definitely need to update the README here though for those that want to install SQLite support for the `soda` binary.

To do that, all you should need is: 

```
go get -u -v -tags sqlite github.com/gobuffalo/pop/soda
```

Looking forward to the PR! :)

**Comment by bigblind** [comment]
I'm assuming it also works if you install all subpackages, as the README currently suggests:

    go get -u -v -tags sqlite github.com/gobuffalo/pop/...
