### ISSUE TITLE
unable to fetch records: sql: Scan error

### ISSUE THREAD

**Issue by olegsobchuk** [gobuffalo/pop#398]
Hi there,
I faced this error during fetching records from DB:
```
unable to fetch records: sql: Scan error on column index 5, name "exchanged": unsupported Scan, storing driver.Value type <nil> into type *nulls.Float64
github.com/gobuffalo/pop.(*Query).All
```
my model:
```
type Tax struct {
	ID        uuid.UUID     `json:"id" db:"id"`
	CreatedAt time.Time     `json:"created_at" db:"created_at"`
	UpdatedAt time.Time     `json:"updated_at" db:"updated_at"`
	Exchanged nulls.Float64 `form:"-" db:"exchanged"`
}
```
Thanks

**Comment by mclark4386** [comment]
@olegsobchuk would you mind shifting the import from `github.com/gobuffalo/pop/nulls` to `github.com/gobuffalo/nulls` and seeing if that changes anything?

**Comment by olegsobchuk** [comment]
@mclark4386  thx, your suggestion works as expected. Would be good to add it to documentation

**Comment by stanislas-m** [comment]
I upgraded `buffalo fix` to help with the transition to the new package.
