### ISSUE TITLE
Allow unmarshalling slices.Map to nil map

### ISSUE THREAD

**Issue by ThePrzeglo** [gobuffalo/pop#417]
I've tried to bind from JSON request struct:
```
cmt := Comment{
    // Data: slices.Map{}, // after uncomment works
}
c.Bind(&cmt)
```
```
type Comment struct {
	ID        uuid.UUID  `json:"id" db:"id"`
	CreatedAt time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt time.Time  `json:"updated_at" db:"updated_at"`
	Data      slices.Map `json:"data" db:"data"`
}
```
And it turned out that it crashes on slices.Map on line 51 with `assignment to entry in nil map`
https://github.com/gobuffalo/pop/blob/master/slices/map.go#L51
Small change to UnmarshalJSON seems to fix issue:
```
func (m *Map) UnmarshalJSON(b []byte) error { // ptr here
	var stuff map[string]interface{}
	err := json.Unmarshal(b, &stuff)
	if err != nil {
		return err
	}
	if *m == nil { // if map that this pointer points to is nil:
		*m = Map{} //  allocate new one
	}
	for key, value := range stuff {
		(*m)[key] = value
	}
	return nil
}
```

**Comment by kiambogo** [comment]
In fact, using `map[string]interface{}` instead of the alias `slices.Map` will work and provides the same functionality. At this point, I'm not sure what benefit slices.Map offers as an alias to `map[string]interface{}`.
