### ISSUE TITLE
Column names are unquoted inserts

### ISSUE THREAD

**Issue by mickeyreiss** [gobuffalo/pop#42]
Resurrecting https://github.com/markbates/pop/issues/113 and https://github.com/markbates/pop/pull/114 as this is still an open issue:

> You should quote column names when executing an insert query (create, save).
> If you have a column named 'end', the execution will fail with pq: syntax error at or near "end".
>
> So,
>
> INSERT INTO mytable (created_at, duration, foo, bar) VALUES (:created_at, :duration, :foo, :bar) > returning id
> should end up as
>
> INSERT INTO mytable ("created_at", "duration", "foo", "bar") VALUES (:created_at, :duration, :foo, 
:bar) returning id
> This was tested on latest postgresql.

A proper solution will need to take into account the SQL Dialect. For instance, MySQL requires backticks, rather than quotes.

**Comment by gpedro** [comment]
this is not the best solution, i known, but works (temporarily) for me 
```
# columns/columns.go
func (c Columns) String() string {
	xs := []string{}
	for _, t := range c.Cols {
		xs = append(xs, t.Name)
	}
	sort.Strings(xs)
	if len(xs) == 0 {
		return ""
	}
       // workaround here :cat:
	return "\"" + strings.Join(xs, "\", \"") + "\""
}
```

**Comment by stanislas-m** [comment]
Fixed.
