### ISSUE TITLE
[Question] How use for/range on a resultset?

### ISSUE THREAD

**Issue by badstorm** [gobuffalo/pop#423]
## Description
Reading the documentation i don't understand how use for/range on a result set.
My intent is to create a new map with some fields of a model.

### Steps to Reproduce the Problem
In my action I'm doing this:
```
tx, ok := c.Value("tx").(*pop.Connection)
if !ok {
    return fmt.Errorf("no transaction found")
}

db_mymodels := &models.MyModels{}
if err := tx.All(db_mymodels); err != nil {
    return err
}

m := make(map[string]string)
for _,rt := range db_mymodels{
    m[rt.Name] = rt.ID
}
c.Set("mymodels", m)
```

### Expected Behavior
I want a map with a [Name]=ID for each item in MyModel table.

### Actual Behavior

I get this erorr:
`cannot range over db_mymodels (type *models.MyModels)`

### Info
pop v4.11.3

**Comment by stanislas-m** [comment]
Hello! `db_mymodels` is declared as a pointer, and you can't use `range` on a pointer of slice.

Try moving the `&` to where it's needed, and it should work fine:

```go
db_mymodels := models.MyModels{}
if err := tx.All(&db_mymodels); err != nil {
    return err
}
```
