### ISSUE TITLE
Model generation issues

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/pop#440]
## Description

Model generator is behaving in an unusual way. Some missing fields and 

### Steps to Reproduce the Problem

  1. Generate a model with: 
```
buffalo db g model team_membership id:uuid team_id:uuid team_grouping_id:uuid since:datetime until:datetime
```

### Expected Behavior

- Model should be generated under the models folder
- Migrations should be generated under the migrations folder
- Model should have an ID
- Model class should compile
- Migration table name should be plural
- Migration should include id:uuid column

### Actual Behavior

- Model is generated under the models folder 
- Migration is generated under the migrations folder 
- Model file doesn't have an ID field
- Model has an invalid validator name which causes it wont compile.
```
&validators.Time.TimeIsPresent{Field: t.Since, Name: "Since"},
```
- Migration table name is singular
- Migration doesn't include id column

### Info
I'm using:
github.com/gobuffalo/buffalo-pop v1.22.0

**Comment by stanislas-m** [comment]
@paganotoni Can you try with this fix? #442 I couldn't reproduce `Model file doesn't have an ID field` though.

**Comment by paganotoni** [comment]
How do I test that branch? I tried by commit number by running: 
```
go get -u -v github.com/gobuffalo/pop@85482504ce9e0d73bf1659d5039ea0dcc802b92f
```
but I still see the issue.

**Comment by paganotoni** [comment]
Oh regarding the ID, the one missing is the migration ID. Not the model ID. It happens when you don't specify an id field in the passed Attributes. Sorry for the confusion.

**Comment by stanislas-m** [comment]
> How do I test that branch? I tried by commit number by running:
> 
> ```
> go get -u -v github.com/gobuffalo/pop@85482504ce9e0d73bf1659d5039ea0dcc802b92f
> ```
> 
> but I still see the issue.

You need to git clone the branch, then execute `make install`. :)

**Comment by paganotoni** [comment]
Thanks. Did that. but now i'm getting:
```
Error: template: -path-/-name-.go.tmpl:58: function "trim_package" not defined
```

**Comment by Icaro-Lima** [comment]
Same problem here, any updates?

**Comment by stanislas-m** [comment]
I'll finish the fix this week-end, I've got a busy week.

**Comment by paganotoni** [comment]
Thanks @stanislas-m !
