### ISSUE TITLE
how can set association_foreignkey in Relationships

### ISSUE THREAD

**Issue by hookover** [gobuffalo/pop#456]
```
type User struct {
      id  int64
      book_id int64  
      books Books `has_many:"books" fk_id:"book_id"` //how can set User.book_id in here
}

type Books struct {
     book_id int64
}
```

please help me. thinks

**Comment by larrymjordan** [comment]
@hookover the use for `fk_id` is not correct.  The correct definition for both models to represent a one to many relationship in pop is as follow:

```
type User struct {
      ID        int64   `db:"id"`
      Books Books  `has_many:"books"`
}

type Books []Book // books should be a slice/array of `Book`

type Book struct {
     UserID  int64  `db:"user_id"`  //user_id is the foreign key used by pop to connect both models by default
}
```

If you've already defined a different foreign key in your database for the `books` table that is different from `user_id` then you should specify it with `fk_id`. example:

```
type User struct {
      ID        int64   `db:"id"`
      Books Books  `has_many:"books" fk_id:"reader_id"`
}

type Books []Book // books should be a slice/array of `Book`

type Book struct {
     ReaderID  int64  `db:"reader_id"`  // Because this is different from user_id
}
```

For a more complete guideline about this, take a look at the [gobuffalo doc](https://gobuffalo.io/en/docs/db/relations/#available-struct-tags) or this [post](https://blog.wawand.co/posts/has-many-in-buffalo-pop-4da9cb8b-6adb-42bf-9411-c4e742b531d2)

Hope this help
