### ISSUE TITLE
Do you have to rely on the model when querying data?

### ISSUE THREAD

**Issue by hookover** [gobuffalo/pop#462]
RawQuery.All(&model)

Is there a way not to rely on model?

like this:
```
data := make([]*map[string]interface{},0)  OR make([]*map[string]sqlx.types,0) 

models.DB.RawQuery("select u.id as uid,u.name,u.phone,u,email, a.money from user as u left join account as a on u.id=a.uid limit 10").Get(&data)

for _,row := range data {
     for field, val:=range row {
               //The field property is the column name
               //The val property is the column value      
     }
}
``

**Comment by stanislas-m** [comment]
I'm afraid you can't do that with pop. Maybe using https://golang.org/pkg/database/sql/#Rows.Columns, but it seems to be a very hard way to handle your data.

**Comment by hookover** [comment]
> I'm afraid you can't do that with pop. Maybe using https://golang.org/pkg/database/sql/#Rows.Columns, but it seems to be a very hard way to handle your data.

Do I have to construct an extra model for each query structure in the face of complex queries?

**Comment by hookover** [comment]
q := models.DB.leftJoin("books","users.id = books.uid").Paginate(page, pageSize).
Select("users.*","books.*").All( &model )

How should this model be constructed？

like this?: 
type model struct {
     Username string `db:"username"`,
     Age string `db:"age"`,
     BookName string `db:"book_name"`,
     BookID int64 `db:"book_id"`,
}
fun (m *model) TableName() {
      return "users"
}

This is so exhausting.
