### ISSUE TITLE
composite primary key not allowed

### ISSUE THREAD

**Issue by nighter7** [gobuffalo/pop#465]
## Description

While trying to create a table based in the following Fizz, Pop does not like it:
```
create_table("policies_resources") {
	t.Column("policy_id", "uuid", {primary: true})
	t.Column("resource_id", "uuid", {primary: true})
        t.DisableTimestamps()
}
```

### Steps to Reproduce the Problem

 Excecute the  previous fizz with buffalo-pop pop migrate up

### Expected Behavior

Fizz DSL must support composite primary key as the underlying RDBMS does

### Actual Behavior

Error message:
```
error processing migrations\20191117082056_create_users_roles.up.fizz: could not fizz the migration migrations\20191117082056_create_users_roles.up.fizz: line 0: could not call create_table function: could not call t.Column function: could not define multiple primary keys
```

### Info

buffalo-pop: v4.12.2
OS: Win 10

**Comment by stanislas-m** [comment]
See https://github.com/gobuffalo/fizz#composite-primary-key, it should solve your case. :)
