### ISSUE TITLE
Arbitrary struct field name for belongs_to relation leads to error with eager creation.

### ISSUE THREAD

**Issue by aeneasr** [gobuffalo/pop#469]
## Description

When using a `has_many` relation, it seems to be impossible to set the child's struct field name of the foreign key, instead `<name>ID` is apparently required.

### Steps to Reproduce the Problem

```
type Request struct {
	ID            uuid.UUID `json:"id" db:"id" rw:"r"`
	CreatedAt     time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	Methods    Methods               `json:"-" has_many:"methods"`
}

type Method struct {
	ID        uuid.UUID `json:"id" db:"id" rw:"r"`

	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAtF time.Time `json:"updated_at" db:"updated_at"`

	
	RequestFoo  uuid.UUID  `json:"-" db:"request_id"`
	
	Request   *Request  `json:"request" belongs_to:"request" fk_id:"RequestFoo"`

	// Doesn't work either:
	// Request   *Request  `json:"request" belongs_to:"request" fk_id:"request_id"`
}

func TestRequest(t *testing.T) {
	req := models.Request{
		Methods: []models.Method{{}},
	}
	_, err = tx.Eager().ValidateAndSave(&req)
	require.NoError(t, err)
}
```

With fizz

```
create_table("requests") {
	t.Column("id", "uuid", {primary: true})
	t.Timestamps()
}

create_table("methods") {
	t.Column("id", "uuid", {primary: true})
	t.Timestamps()
	t.Column("request_id", "uuid")
       t.ForeignKey("request_id", {"requests": ["id"]}, {"on_delete": "cascade"})
}
```

Will always result in: `could not set '3aecf318-0fb6-43b3-b3fe-a0de91042f65' in '<invalid reflect.Value>'` (or some other uuid value).

Only changing `RequestFoo` to `RequestID` resolves the issue:

### Expected Behavior

I would expect the struct field name to be customizable. I would also expect this to work if `RequestID` was missing from the struct:

```
type Method struct {
	ID        uuid.UUID `json:"id" db:"id" rw:"r"`

	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`

	Request   *Request  `json:"request" belongs_to:"request" fk_id:"request_id"`
}
```

I would also expect the behavior to reflect other struct fields with `db` tags. This works with eager fetching, but not eager creation.

### Actual Behavior

It seems like this is some fixed behavior. This is also not explained in the [docs](https://gobuffalo.io/en/docs/db/relations/onetomany/).

### Info

Using pop latest master without buffalo.

**Comment by stanislas-m** [comment]
Fixed with #546.
