### ISSUE TITLE
Timestamps should default now()

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/pop#486]
This would make a lot of things easier, things like fixtures and SQL inserts would become simpler with this change.

**Comment by cmhakkim** [comment]
Duplicate of https://github.com/gobuffalo/pop/issues/455 but the issue is still valid.

**Comment by cmhakkim** [comment]
Oh. I'm circumventing this by using database defaults triggers to set timestamps and I've marked these columns as read-only with `rw:"r"` tag.
