### ISSUE TITLE
Allow to run SQL via `soda migrate` outside of transaction.

### ISSUE THREAD

**Issue by mavenraven** [gobuffalo/pop#499]
Hi @stanislas-m ! Thank you for making `soda`! We're currently using it for our database needs, but we're going to have to migrate to a different tool or fork `soda` due to the following use case:

We have a production instance of Postgres where things like this are unacceptable from an SLO standpoint: https://leopard.in.ua/2016/09/20/safe-and-unsafe-operations-postgresql . For example, we need to use `CREATE INDEX CONCURRENTLY` instead of `CREATE INDEX` on existing tables. However, this cannot be run in a transaction, so soda can't run it.

Another example is: https://stackoverflow.com/questions/1771543/adding-a-new-value-to-an-existing-enum-type/41696273#41696273

So, we need a way to disable transactions, either globally or on a per file basis [it doesn't matter to me]. I was going to fork `soda` and make this function a no-op: https://github.com/gobuffalo/pop/blob/master/connection.go#L132 , but ideally we could get something that was mergeable upstream. I'm happy to some time in a PR if you agree that this is valuable and we can have a shared understanding on the UX and implementation. Thanks!

**Comment by cmhakkim** [comment]
Couldn't you just execute that migration in code after program startup "if migration X is the last applied migration" i.e. make your own migration handler for that special case?

I don't know what you're doing but if it involves multiple server instances there might be something else you need to take into account too.

**Comment by mavenraven** [comment]
@cmhakkim no, that doesn't make sense for this use case. The problem I'm talking about is why https://www.percona.com/doc/percona-toolkit/LATEST/pt-online-schema-change.html and https://github.com/github/gh-ost exist.

This doesn't matter to me personally anymore as I'm no longer using soda, so I'm going to close the issue.
