### ISSUE TITLE
mysql dialect URL returns without scheme

### ISSUE THREAD

**Issue by zepatrik** [gobuffalo/pop#538]
## Description

`mysql.URL()` returns the url without the scheme `mysql://` while postgres and cockroach dialects add that scheme. Is there any reason for doing that or should I fix it?

### Steps to Reproduce the Problem

``` go
c, err := pop.NewConnection&pop.ConnectionDetails{
    URL: "mysql://url",
})
require.NoError(t, err)
```

### Expected Behavior

``` go
strings.HasPrefix(c.URL(), "mysql://") == true
```

### Actual Behavior

``` go
strings.HasPrefix(c.URL(), "mysql://") == false
```

**Comment by stanislas-m** [comment]
I don't think there's a reason for that, you can fix it. :)

**Comment by aeneasr** [comment]
Closing, see https://github.com/gobuffalo/pop/pull/544#issuecomment-754475577
