### ISSUE TITLE
Fizz migrations don't care about the return value from exec() 

### ISSUE THREAD

**Issue by akostibas** [gobuffalo/pop#54]
Fizz supports running external commands with `exec` (https://github.com/gobuffalo/pop/tree/master/fizz#execute-an-external-command).

I would expect that if the command doesn't exit cleanly, the migration would fail. Instead, it continues on as if nothing was wrong. This is preventing me from using this functionality in any meaningful way.

**Comment by akostibas** [comment]
I've created a patch that produces the desired behavior, but it is extremely crude. I'd love some help turning this into a more appropriate solution.

https://github.com/akostibas/pop/tree/ak-fix-exec-errors

**Comment by PetarAtanasov** [comment]
@stanislas-m should this issue be closed?

**Comment by akostibas** [comment]
Yeah this should be resolved.
