### ISSUE TITLE
EagerPreload not loading same associations as Eager

### ISSUE THREAD

**Issue by reggieriser** [gobuffalo/pop#547]
## Description

In testing out the new `EagerPreload` functionality, I noticed two scenarios where associations did not appear to be populated with `EagerPreload` but were populated with `Eager`:

1. Fetching a `belongs_to` association for an optional field when it's represented as a pointer (if represented as one of the `nulls` types, it works fine).
1. Fetching more than one nested `belongs_to` association at the same level results in only the last one being populated.

### Steps to Reproduce the Problem

Here's an [example query](https://github.com/transcom/mymove/blob/60e448c385b261ed3397eb1be3823227c707a0ec/pkg/handlers/primeapi/move_task_order.go#L38-L39) and the [relevant part of the model](https://github.com/transcom/mymove/blob/60e448c385b261ed3397eb1be3823227c707a0ec/pkg/models/mto_shipments.go#L64-L67).

The first problem noted above seems to be triggered by the pointer UUID fields.  After I changed those to `nulls.UUID` that problem went away, but the second problem above emerged.

### Expected Behavior

I expected `EagerPreload` would result in the same associations being loaded as `Eager`.

### Actual Behavior

Some associations did not appear to load.

### Info

Mac OS X Catalina, Postgres, latest Pop development branch, and not using through Buffalo.

**Comment by JustGAST** [comment]
Excuse me for intrusion into your issue, but I can add, that EagerPreload not loading many-to-many relations. Killed one day to find it out. Ended with creating new project with Users and Addresses models from documentation and it worked. But not when I switched to EagerPreload mode. 

Mac OS X Mojave and MySQL. Using through Buffalo.

**Comment by aeneasr** [comment]
#602 is merged
