### ISSUE TITLE
Wrong postgresql error messages because of switch to jackc/pgx

### ISSUE THREAD

**Issue by karlhaas** [gobuffalo/pop#570]
## Description

jackc/pgx behaves differently compared to the previously used driver lib/pq. Before upgrading a DB error was reported like:

`pq: duplicate key value violates unique constraint ...`

After upgrading the same error is reported like:

`failed to close statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)`

This makes it very hard to find the cause of the error.

### Steps to Reproduce the Problem

For example: create the same object (model with same uuid) twice

### Expected Behavior

Error should be: `pq: duplicate key value violates unique constraint ...`

### Actual Behavior

Error is: `failed to close statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)``

### Info

Pop version v5.2.0

**Comment by karlhaas** [comment]
Maybe the causing error should be reported and not the error of stmt.Close:
https://github.com/gobuffalo/pop/blob/4196733eb565453ad7d66b39e7c49162391bcd44/dialect_common.go#L86-L92

**Comment by stanislas-m** [comment]
Fixed with #569.
