### ISSUE TITLE
invalid recursive type when using has_many and belongs_to

### ISSUE THREAD

**Issue by u007** [gobuffalo/pop#59]
example:
```
class Paper {
  Code Code `json:"code" has_many:"codes"`
}

class Code {
  PaperID uuid `json:"paper_id" db:"paper_id"`
  Paper Paper `json:"paper" belongs_to:"paper"`//if i remove this line, the error wont occur
}

```

throwing error compilation
invalid recursive type Paper

i suspect its due to PaperID

**Comment by u007** [comment]
btw, is there any reason not to use gorm?
i think their belongs to and has many is more complete

but i like the way fizz migration works

**Comment by stanislas-m** [comment]
@u007 In Go, you can't define structs with circular references. You'll need to use a pointer attribute instead.

**Comment by u007** [comment]
did u mean adding pointer to code.Paper ?
```
class Code {
  PaperID uuid `json:"paper_id" db:"paper_id"`
  Paper *Paper `json:"paper" belongs_to:"paper"`//if i remove this line, the error wont occur
}
```

**Comment by stanislas-m** [comment]
Yup, it should work for the Go part. Not sure it's allowed with the Pop side, though.

**Comment by stanislas-m** [comment]
I confirm it works with the pointer.
