### ISSUE TITLE
How can I switch of DB support?

### ISSUE THREAD

**Issue by nitram509** [gobuffalo/pop#593]
Hi,

I'm a beginner in using Buffalo, but like it a lot.
May I ask for some support, because I could not find an answer in the documentation.

## Description

I did create a new microservice and want to disable DB support at all.
So I did comment out the line in app.go: ```app.Use(popmw.Transaction(models.DB))```
Then I was able to run without a DB.

Unfortunately, when I do run ```buffalo test``` it still crashes with error

```ERRO[0000] Error: error creating PostgreSQL database rotor_configs_go_test: dial tcp 127.0.0.1:5432: connect: connection refused```

How can I switch of DB support completely? 
(was not able to find it in the docs, though)

### Info

Running on OSX 10.15.6

**Comment by stanislas-m** [comment]
Hello, one way to do it is using the `soda` command:

```
$ soda generate config -t mysql
```

Or using `buffalo` with the pop plugin:
```
$ buffalo pop generate config -t mysql
```

(replace mysql with the dialect you need. :) )
