### ISSUE TITLE
How can I deactivate DB support?

### ISSUE THREAD

**Issue by nitram509** [gobuffalo/pop#600]
Hi,

This is a duplicate of #593, because it was closed without a solution.
The given solution was to change the DB type via the command ```soda generate config -t ...```.
Unfortunately, the -t option has no support for 'no-db' and thus the 'buffalo test' command is still failing.
I want to write a stateless service, without a DB - so how can I do that?

----

I'm a beginner in using Buffalo, but like it a lot.
May I ask for some support, because I could not find an answer in the documentation.

## Description

I did create a new microservice and want to disable DB support at all.
So I did comment out the line in app.go: ```app.Use(popmw.Transaction(models.DB))```
Then I was able to run without a DB.

Unfortunately, when I do run ```buffalo test``` it still crashes with an error

```ERRO[0000] Error: error creating PostgreSQL database rotor_configs_go_test: dial tcp 127.0.0.1:5432: connect: connection refused```

How can I switch of DB support completely? 
(was not able to find it in the docs, though)

### Info

Running on OSX 10.15.6

/cc @stanislas-m

**Comment by stanislas-m** [comment]
Oh, sorry, I understood "how can I change the DB driver".

Unfortunately, you need to regenerate your app with the `--skip-pop` flag.

```
$ buffalo new myapp --skip-pop
```

**Comment by nitram509** [comment]
Stanislas, thank you very much for your quick reply and support.
