### ISSUE TITLE
Generating model with SQL files instead of Fizz files

### ISSUE THREAD

**Issue by Riverside14** [gobuffalo/pop#61]
Hi,

I was wondering if it could be possible when I'm generating my models to specify which kind of migration file (SQL or Fizz) I want through a flag or something like that ?

I think this kind of feature could offer more flexibility in the migration process. For example, when I want to create a composite primary key. I have to use a little workaround : drop the primary key and execute a raw query.

**Comment by markbates** [comment]
A PR would definitely be welcome.

**Comment by Riverside14** [comment]
Ok great, I will try to see how it works and if I have enough time maybe work on it.

Any infos or guidelines are welcome !

**Comment by markbates** [comment]
Off the top of my head I would suggestion using the fizz package to build the sql for the forest platform, and then dump that into the generated sql file.

**Comment by Riverside14** [comment]
Indeed, using the fizz package works pretty well, but I need to use a ```*pop.Connection``` in order to retrieve the correct ```Dialect``` and generate the good sql file depending the environment.

I saw that there is a function ```getConn()``` in the ```github.com/gobuffalo/pop/soda/cmd``` package.
So far, I passed the function as an argument into a constructor which return the ```ModelCmd```.

Here's a snippet of this :
```go
package generate 

...
type getConnection func() *pop.Connection

func NewModelCmd(f getConnection) *cobra.Command {
	connection = f()
	return ModelCmd
}
```

But it seems very ugly to do so, maybe any of you has an idea about how could I do this ?

**Comment by markbates** [comment]
I definitely wouldn't do that. :)

All the `getConn` function does is check if a connection is in the map. I wouldn't go that far. You can do something as simple as:

```go
eee, err := cmd.Flags().GetString("env")
if err != nil {
	return errors.WithStack(err)
}
db, err := pop.Connect(eee)
```

**Comment by Riverside14** [comment]
I close this issue since the PR #63 was merged
