### ISSUE TITLE
Add configurable limit for counting

### ISSUE THREAD

**Issue by jmduque** [gobuffalo/pop#631]
https://github.com/gobuffalo/pop/blob/5a8f51c37336105490d5c27c25ddf255886ec5d8/finders.go#L350

Right now go-buffalo does not support counting with a limit, this causes that in paginated queries for tables with millions of items, no matter how small amount of items we query per page, the time to execute the query will be directly proportional to the amount of items within the table, and in some extremes, we can see paginated queries take just milliseconds to query the items while taking minutes to query the count.

I propose to have a way to either configure the Paginator model to include a property such as MaxPageCount that is used to limit the amount of pages we count while paginating, as most user facing cases, users will never paginate beyond i.e., 99 pages.

**Comment by sio4** [comment]
It seems like this is a duplication of #394, which is on the backlog. I am going to close this issue, please check the linked issue for future updates.
