### ISSUE TITLE
Upstream Pacakge github.com/mattn/go-sqlite3 sillyness

### ISSUE THREAD

**Issue by james-d-elliott** [gobuffalo/pop#648]
## Description

This is more of a for your information than anything, I believe I've solved this downstream with replace/exclude; though I'd be willing to draft PR's for this if desired. 

The github.com/mattn/go-sqlite3 library updated to v2.0.0-v2.0.6 prematurely, and have decided to release future changes under v1.x.x (currently v1.14.7), they also never correctly upgraded for v2 as the module path did not change.

This means v2.0.3+incompatible which is included in github.com/gobuffalo/nulls@v0.4.0 (which this package relies on that package) includes a fairly outdated version, and there have been various bug fixes since then. I decided to post it here as the highest package in the chain that you control that has this issue is this one.

I have opted not to fill in the other areas as I think that's appropriate, let me know if not!

### Steps to Reproduce the Problem

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Info

N/A

**Comment by sio4** [comment]
Thanks for the comment!
