### ISSUE TITLE
bind vars generation failed when use both `WHERE + IN` and `HAVING`.

### ISSUE THREAD

**Issue by sio4** [gobuffalo/pop#65]
If I use something like `WHERE id in (?)` and `HAVING count(id) = ?` at the same time, it does not compiled expectedly.

The line below is called if there is `in (?)` on SQL which is built by `buildSelectSQL()`, but there is another `?` for `HAVING` and `sqlx.In()` returns error "number of bindVars exceeds arguments". (I cannot sure since I just checked it on `pop` code and did not get into `sqlx` code anyway.)

https://github.com/gobuffalo/pop/blob/8d249c6da60e0731a854aeaab595c1bcd9657bbc/sql_builder.go#L59

IMHO, we can move this lines into `buildWhereClauses()`. Can I open a PR for this?

**Comment by markbates** [comment]
There's a PR already for this issue, https://github.com/gobuffalo/pop/pull/67, should be merged today or tomorrow.

**Comment by stanislas-m** [comment]
Fixed with #67.

**Comment by sio4** [comment]
Nice, it works well!
