### ISSUE TITLE
belongs_to auto save should be off by default

### ISSUE THREAD

**Issue by u007** [gobuffalo/pop#74]
there are times when we do not wish to save belongs_to

https://stackoverflow.com/questions/2231415/does-activerecord-save-a-belongs-to-association-when-saving-main-object

**Comment by u007** [comment]
does anyone know a quick fix for this?

**Comment by markbates** [comment]
https://godoc.org/github.com/gobuffalo/pop#Connection.Eager

**Comment by u007** [comment]
i cant see it anywhere

**Comment by markbates** [comment]
> take a variadic list of associations to load.

In the docs, and  the example. You can pass in a list of associations you want to load with Eagle.

**Comment by stanislas-m** [comment]
@markbates I think the problem here is about Eager creation, not Eager loading.

**Comment by markbates** [comment]
Ah  never mind. I’ve only woken up a little while ago. :) I’ll go have coffee instead. :) Sorry.

**Comment by stanislas-m** [comment]
Fixed in https://github.com/gobuffalo/pop/commit/98e5ce75a2ec5fb0574463a6edec85dd3e758394.
