### ISSUE TITLE
pop.Connection.Transaction can leak connections

### ISSUE THREAD

**Issue by chrisseto** [gobuffalo/pop#748]
## Description

If a user's code panics within a [`pop.Connection.Transaction`](https://github.com/gobuffalo/pop/blob/main/connection.go#L150-L174) closure, `.Rollback` nor `.Commit` will not be called resulting in a leaked SQL connection.

### Steps to Reproduce the Problem

```go
func DoThing(conn *pop.Connection) {
    _ = conn.Transaction(func(tx *pop.Connection) error {
        panic("Oh no, this is probably due to a null pointer exception!")
    })
}
```

### Expected Behavior

`.Transaction` should `recover` panics and attempt to call `.Rollback` before re-panicking the error.

### Actual Behavior

A SQL connection is silently leaked. Depending on your connection pool setting, you might not even notice.

### Info

This issue is not specific to an OS and is observable on the latest `main` commit (4e72fd8f35449c084bd44fee9eedf64ebd2b62b4) as of writing

**Comment by sio4** [comment]
Thank you for reporting the issue. It could be a serious issue if the transaction is not guaranteed even though the root cause is on the user's own code. Will check the sequence but it could take more time.
