### ISSUE TITLE
Empty postgres array loaded as slice with one item

### ISSUE THREAD

**Issue by jakeactually** [gobuffalo/pop#788]
the postgres database contains an empty int array, it looks like this

{}

but connection.Find(model, id) loads the model with a slice that looks like this

[0]

it should leave the slice empty

**Comment by sio4** [comment]
Thanks for reporting this issue. I think the issue is just fixed by #791. Could you please confirm it if you are still available to reproduce this issue?

**Comment by jakeactually** [comment]
> Thanks for reporting this issue. I think the issue is just fixed by #791. Could you please confirm it if you are still available to reproduce this issue?

Yes I think that would solve that. Thanks!
