### ISSUE TITLE
connection.copy is assigning tx to store

### ISSUE THREAD

**Issue by hbpatre** [gobuffalo/pop#79]
connection.copy function is creating copy of connection c and putting "Store:   c.TX", is it correct?

In some cases its creating copy with store as nil, which causes "invalid memory address or nil pointer dereference" error in later steps.

**Comment by stanislas-m** [comment]
That seems to be a typo. :)

**Comment by stanislas-m** [comment]
@hbpatre Can you make a PR to fix it?

**Comment by stanislas-m** [comment]
Fixed with #80.
