### ISSUE TITLE
bug: transaction panic recovery swallows panic message

### ISSUE THREAD

**Issue by xanderman** [gobuffalo/pop#793]
#### Description

When using transactions, any panic that occurs in the function passed to `pop.Transaction` is recovered and swallowed. The recovered error is checked for `nil`, but otherwise ignored. The error returned from the transaction is simply `fmt.Errorf("transaction was rolled back due to inner panic")`. There's no way to figure out what the panic was, because the original error is not wrapped, nor is it logged. This is especially problematic when using `popmw`, because _every_ request is wrapped in a transaction automatically, and now ~all panics are swallowed and undiagnosable.

#### Expected Behavior

The recovered error should be logged and/or wrapped by the returned error.

#### Actual Behavior

The recovered error is swallowed entirely. The returned generic error does generally ensure the request fails with a 500 response, but it's basically impossible to tell what caused the issue.

### To Reproduce

Use `app.User(popmw.Transaction(models.DB)`, then add a panic to a handler. Observe that the logs contain "transaction was rolled back due to inner panic", but not the details of the panic.

**Comment by sio4** [comment]
Agree. It should be fixed soon, and I am working on it. Some points are:

* the panic should be recovered **from Pop** to prevent possible connection leak
  * if the panic finally recovered from the main application, the open connection with the transaction will be leaked
  * panic again after rolling back could be an option
* Buffalo has its own panic handler middleware so consolidating into it could be better
* Buffalo's panic handler emits an event for panic, so developers could configure a listener to check the details

The current workaround could be recovering the panic from your own handler to see what happened.

**Comment by sio4** [comment]
We have an open PR for the same code block so the fix will be done after merging that, and will be released as v6.1.0 soon.

**Comment by sio4** [comment]
The bug was fixed and the fix will be included in the next release (maybe v6.1.0)
