### ISSUE TITLE
feature: improve performance if the element of the Value of *Model does not implement the AfterFindable interface.

### ISSUE THREAD

**Issue by seedeed** [gobuffalo/pop#799]
### Description

I found that the afterFind method of *Model would create a log of goroutines via *errgroup.Group.Go(...) even if the element of the Value of *Model does not implement the AfterFindable interface, which might cause a lot of unneeded CPU cost. To avoid this, I think we could move the AfterFindable interface checking out of the Go function. If this's really a problem, I think I could submit a PR to fix it. 

https://github.com/gobuffalo/pop/blob/17f09c0bd07243eb4c8f43cddeadb556c24235d1/callbacks.go#L32-L43

**Comment by sio4** [comment]
Hi @seedeed, Thank you for reporting this issue. I agree with you, the block could spend unnecessary resources.

The block was recently touched with a new thing, and I opened a PR for your issue after that. The PR is #805, and the specific commit is 89774fa. Please take a look at the PR and/or the commit and give me feedback if the direction is the same as your idea, or please let me know your idea if you have another good way.

Thanks in advance!

**Comment by sio4** [comment]
Hi @seedeed 
I just merged my PR into the main. If you have any idea about it, please let me know.
