### ISSUE TITLE
Need a way to update stale pop connecton configs before pop reconnections a failed connectionfeature: 

### ISSUE THREAD

**Issue by chakramarla** [gobuffalo/pop#813]
### Description

We use db credentials which expires after 15 mins. The pop connections work fine for some period of time, because of either idle time or some network issue, pop tries to open new connection with stale db creds. This is causing connection failures.
Is there a way to reset connection configs regularly? If not I don't see any workaround for this issue, we need some callback before newconnection/openconnection call where user can reset db creds/configs.

**Comment by chakramarla** [comment]
We use iam rds tokens which expires

**Comment by sio4** [comment]
> Is there a way to reset connection configs regularly? If not I don't see any workaround for this issue, we need some callback before newconnection/openconnection call where user can reset db creds/configs.

The connection information is just configured when it is initialized and Pop does not support periodic reconfiguration.

Anyway, it is interesting to me, and I would like to ask you for the details of how you configured it initially and what could be the best approach for your condition. Could you please explain more with some examples of your configuration?

**Comment by chakramarla** [comment]
sio4, thanks for response. 
We use AWS IAM rds tokens for db authentication which expire after 15 mins.
Here is the AWS sample code for db connection using IAM authentication
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.Go.html

Here is my code snippet:
        cfg, err := config.LoadDefaultConfig(context.TODO())
	if err != nil {		
		panic("configuration error: " + err.Error())
	}
	env := envy.Get("GO_ENV", "development")
	authenticationToken, err := auth.BuildAuthToken(context.TODO(), dbEndpoint, region, dbUser, cfg.Credentials)
	if err != nil {
		panic("failed to create authentication token: " + err.Error())		
	}
	dsn := fmt.Sprintf("%s:%s@tcp(%s)/%s?allowCleartextPasswords=true&parseTime=true&multiStatements=true&tls=true",
		dbUser, authenticationToken, dbEndpoint, dbName,
	)
	var connection *pop.Connection
	DB, err = pop.NewConnection(&pop.ConnectionDetails{
		Dialect: "mysql",
		URL:     dsn,
	})
       if err != nil {
           panic("failed to create db connection error: " + err)
       }
      if err = DB.Open(); err != nil {
          panic("failed to open db connection error: " + err)
      }

The db connection works even after 15 mins, it fails only when it tries to reopen connection after a db disconnected.
Appreciate your help.
