### ISSUE TITLE
Slack Channel Not Working

### ISSUE THREAD

**Issue by Aritra8438** [gobuffalo/pop#831]
While working with `pop`, I got interested in the working of pop and how query concatenation is implemented in pop.

Therefore, I tried to join the **slack channel**, but it requires my email to be registered with the workspace.

**Comment by briskt** [comment]
I see your messages on the #buffalo channel of the Gophers Slack, so it looks like you've found a solution for this. Can this issue be closed?

**Comment by Aritra8438** [comment]
Yes, @briskt. But, the slack channel link in the issue choice page is not working though!

**Comment by briskt** [comment]
> Yes, @briskt. But, the slack channel link in the issue choice page is not working though!

Oh, I see. Thanks for mentioning that. Perhaps @sio4 or @stanislas-m can update the link in the `ISSUE_TEMPLATE` folder.
