### ISSUE TITLE
the hook about time have an error

### ISSUE THREAD

**Issue by destinyjingkun** [gobuffalo/pop#89]
![image](https://user-images.githubusercontent.com/19849328/39915482-aac43492-553a-11e8-8841-fa996810092c.png)

![image](https://user-images.githubusercontent.com/19849328/39915641-0285a9ae-553b-11e8-8fc5-002df51a733c.png)

**Comment by markbates** [comment]
CreatedAt and Updated timestamps and are managed by pop. Currently they’re not user setable.
