### ISSUE TITLE
Missing Documention Clone Function

### ISSUE THREAD

**Issue by alphonse927** [gobuffalo/pop#90]
Recently I noticed that the Clone Function doesn't have any information, no docs, nothing.

I noticed this because I was using a query inside a range, and for each cycle the query was appending the next value. A friend of mine has to explain me how the Clone Function works.
Thanks.

**Comment by stanislas-m** [comment]
@alphonse927 Do you want to work on this one? :)

**Comment by stanislas-m** [comment]
Fixed with #107.
