### ISSUE TITLE
Select support (#78) does not work for postgres

### ISSUE THREAD

**Issue by robbyoconnor** [gobuffalo/pop#99]
#78 isn't working for postgres: 

I am getting the following: 

```
pq: syntax error at or near "AS"
```

Code: 
```go
err = as.DB.Select("refresh_token").First(&user)
```

**Comment by robbyoconnor** [comment]
I think I know the issue -- it's not a bug

**Comment by robbyoconnor** [comment]
Yeh no bug :) -- I'm a moron.

**Comment by mclark4386** [comment]
lol We all have our moments^^ Glad you got it figured out!
